/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * API version: 1.0
 * Contact: hello@merge.dev
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merge_crm_client

import (
	"encoding/json"
)

// PatchedEngagementEndpointRequest struct for PatchedEngagementEndpointRequest
type PatchedEngagementEndpointRequest struct {
	Model PatchedEngagementRequest `json:"model"`
	// raw json response by property name
	ResponseRaw map[string]json.RawMessage `json:"-"`
}

// NewPatchedEngagementEndpointRequest instantiates a new PatchedEngagementEndpointRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedEngagementEndpointRequest(model PatchedEngagementRequest) *PatchedEngagementEndpointRequest {
	this := PatchedEngagementEndpointRequest{}
	this.Model = model
	return &this
}

// NewPatchedEngagementEndpointRequestWithDefaults instantiates a new PatchedEngagementEndpointRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedEngagementEndpointRequestWithDefaults() *PatchedEngagementEndpointRequest {
	this := PatchedEngagementEndpointRequest{}
	return &this
}

// GetModel returns the Model field value
func (o *PatchedEngagementEndpointRequest) GetModel() PatchedEngagementRequest {
	if o == nil {
		var ret PatchedEngagementRequest
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *PatchedEngagementEndpointRequest) GetModelOk() (*PatchedEngagementRequest, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *PatchedEngagementEndpointRequest) SetModel(v PatchedEngagementRequest) {
	o.Model = v
}

func (o PatchedEngagementEndpointRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["model"] = o.Model
	}
	return json.Marshal(toSerialize)
}

func (v *PatchedEngagementEndpointRequest) UnmarshalJSON(src []byte) error {
    type PatchedEngagementEndpointRequestUnmarshalTarget PatchedEngagementEndpointRequest

	var intermediateResult PatchedEngagementEndpointRequestUnmarshalTarget
	var err1 = json.Unmarshal(src, &intermediateResult)
    if err1 != nil {
        return err1
    }
    var err2 = json.Unmarshal(src, &intermediateResult.ResponseRaw)
	if err2 != nil {
		return err2
	}

	*v = PatchedEngagementEndpointRequest(intermediateResult)
	return nil
}
type NullablePatchedEngagementEndpointRequest struct {
	value *PatchedEngagementEndpointRequest
	isSet bool
}

func (v NullablePatchedEngagementEndpointRequest) Get() *PatchedEngagementEndpointRequest {
	return v.value
}

func (v *NullablePatchedEngagementEndpointRequest) Set(val *PatchedEngagementEndpointRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedEngagementEndpointRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedEngagementEndpointRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedEngagementEndpointRequest(val *PatchedEngagementEndpointRequest) *NullablePatchedEngagementEndpointRequest {
	return &NullablePatchedEngagementEndpointRequest{value: val, isSet: true}
}

func (v NullablePatchedEngagementEndpointRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedEngagementEndpointRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	var err1 = json.Unmarshal(src, &v.value)
    if err1 != nil {
        return err1
    }
    return json.Unmarshal(src, &v.value.ResponseRaw)
}


