/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * API version: 1.0
 * Contact: hello@merge.dev
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merge_crm_client

import (
	"encoding/json"
)

// PatchedCRMCustomObjectEndpointRequest struct for PatchedCRMCustomObjectEndpointRequest
type PatchedCRMCustomObjectEndpointRequest struct {
	Model CustomObjectRequest `json:"model"`
	// raw json response by property name
	ResponseRaw map[string]json.RawMessage `json:"-"`
}

// NewPatchedCRMCustomObjectEndpointRequest instantiates a new PatchedCRMCustomObjectEndpointRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedCRMCustomObjectEndpointRequest(model CustomObjectRequest) *PatchedCRMCustomObjectEndpointRequest {
	this := PatchedCRMCustomObjectEndpointRequest{}
	this.Model = model
	return &this
}

// NewPatchedCRMCustomObjectEndpointRequestWithDefaults instantiates a new PatchedCRMCustomObjectEndpointRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedCRMCustomObjectEndpointRequestWithDefaults() *PatchedCRMCustomObjectEndpointRequest {
	this := PatchedCRMCustomObjectEndpointRequest{}
	return &this
}

// GetModel returns the Model field value
func (o *PatchedCRMCustomObjectEndpointRequest) GetModel() CustomObjectRequest {
	if o == nil {
		var ret CustomObjectRequest
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *PatchedCRMCustomObjectEndpointRequest) GetModelOk() (*CustomObjectRequest, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *PatchedCRMCustomObjectEndpointRequest) SetModel(v CustomObjectRequest) {
	o.Model = v
}

func (o PatchedCRMCustomObjectEndpointRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["model"] = o.Model
	}
	return json.Marshal(toSerialize)
}

func (v *PatchedCRMCustomObjectEndpointRequest) UnmarshalJSON(src []byte) error {
    type PatchedCRMCustomObjectEndpointRequestUnmarshalTarget PatchedCRMCustomObjectEndpointRequest

	var intermediateResult PatchedCRMCustomObjectEndpointRequestUnmarshalTarget
	var err1 = json.Unmarshal(src, &intermediateResult)
    if err1 != nil {
        return err1
    }
    var err2 = json.Unmarshal(src, &intermediateResult.ResponseRaw)
	if err2 != nil {
		return err2
	}

	*v = PatchedCRMCustomObjectEndpointRequest(intermediateResult)
	return nil
}
type NullablePatchedCRMCustomObjectEndpointRequest struct {
	value *PatchedCRMCustomObjectEndpointRequest
	isSet bool
}

func (v NullablePatchedCRMCustomObjectEndpointRequest) Get() *PatchedCRMCustomObjectEndpointRequest {
	return v.value
}

func (v *NullablePatchedCRMCustomObjectEndpointRequest) Set(val *PatchedCRMCustomObjectEndpointRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedCRMCustomObjectEndpointRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedCRMCustomObjectEndpointRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedCRMCustomObjectEndpointRequest(val *PatchedCRMCustomObjectEndpointRequest) *NullablePatchedCRMCustomObjectEndpointRequest {
	return &NullablePatchedCRMCustomObjectEndpointRequest{value: val, isSet: true}
}

func (v NullablePatchedCRMCustomObjectEndpointRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedCRMCustomObjectEndpointRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	var err1 = json.Unmarshal(src, &v.value)
    if err1 != nil {
        return err1
    }
    return json.Unmarshal(src, &v.value.ResponseRaw)
}


