/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * API version: 1.0
 * Contact: hello@merge.dev
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merge_crm_client

import (
	"encoding/json"
)

// PatchedOpportunityEndpointRequest struct for PatchedOpportunityEndpointRequest
type PatchedOpportunityEndpointRequest struct {
	Model PatchedOpportunityRequest `json:"model"`
	// raw json response by property name
	ResponseRaw map[string]json.RawMessage `json:"-"`
}

// NewPatchedOpportunityEndpointRequest instantiates a new PatchedOpportunityEndpointRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedOpportunityEndpointRequest(model PatchedOpportunityRequest) *PatchedOpportunityEndpointRequest {
	this := PatchedOpportunityEndpointRequest{}
	this.Model = model
	return &this
}

// NewPatchedOpportunityEndpointRequestWithDefaults instantiates a new PatchedOpportunityEndpointRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedOpportunityEndpointRequestWithDefaults() *PatchedOpportunityEndpointRequest {
	this := PatchedOpportunityEndpointRequest{}
	return &this
}

// GetModel returns the Model field value
func (o *PatchedOpportunityEndpointRequest) GetModel() PatchedOpportunityRequest {
	if o == nil {
		var ret PatchedOpportunityRequest
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *PatchedOpportunityEndpointRequest) GetModelOk() (*PatchedOpportunityRequest, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *PatchedOpportunityEndpointRequest) SetModel(v PatchedOpportunityRequest) {
	o.Model = v
}

func (o PatchedOpportunityEndpointRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["model"] = o.Model
	}
	return json.Marshal(toSerialize)
}

func (v *PatchedOpportunityEndpointRequest) UnmarshalJSON(src []byte) error {
    type PatchedOpportunityEndpointRequestUnmarshalTarget PatchedOpportunityEndpointRequest

	var intermediateResult PatchedOpportunityEndpointRequestUnmarshalTarget
	var err1 = json.Unmarshal(src, &intermediateResult)
    if err1 != nil {
        return err1
    }
    var err2 = json.Unmarshal(src, &intermediateResult.ResponseRaw)
	if err2 != nil {
		return err2
	}

	*v = PatchedOpportunityEndpointRequest(intermediateResult)
	return nil
}
type NullablePatchedOpportunityEndpointRequest struct {
	value *PatchedOpportunityEndpointRequest
	isSet bool
}

func (v NullablePatchedOpportunityEndpointRequest) Get() *PatchedOpportunityEndpointRequest {
	return v.value
}

func (v *NullablePatchedOpportunityEndpointRequest) Set(val *PatchedOpportunityEndpointRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedOpportunityEndpointRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedOpportunityEndpointRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedOpportunityEndpointRequest(val *PatchedOpportunityEndpointRequest) *NullablePatchedOpportunityEndpointRequest {
	return &NullablePatchedOpportunityEndpointRequest{value: val, isSet: true}
}

func (v NullablePatchedOpportunityEndpointRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedOpportunityEndpointRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	var err1 = json.Unmarshal(src, &v.value)
    if err1 != nil {
        return err1
    }
    return json.Unmarshal(src, &v.value.ResponseRaw)
}


